from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class IBackupSDK(Protocol):
    async def create_backup(self) -> str: ...
    async def restore_backup(self, backup_path: str) -> bool: ...
    async def list_backups(self) -> list[dict]: ...
