from __future__ import annotations
from typing import Protocol, runtime_checkable, Any

@runtime_checkable
class IConnectorSDK(Protocol):
    async def call(self, connector: str, action: str, params: dict | None = None) -> Any: ...
    async def list_connectors(self) -> tuple[str, ...]: ...
    async def check_health(self, connector: str) -> bool: ...
