from __future__ import annotations
from typing import Protocol, runtime_checkable
from core.domain.engine import EngineDescriptor, HealthStatus

@runtime_checkable
class IEngine(Protocol):
    @property
    def descriptor(self) -> EngineDescriptor: ...
    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def health(self) -> HealthStatus: ...
