from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class IExperienceSDK(Protocol):
    async def record_execution(self, runtime: str, model: str, tokens_per_second: float, success: bool) -> None: ...
    async def get_best_runtime(self, model: str) -> str | None: ...
    async def get_stats(self) -> dict: ...
