from __future__ import annotations
from typing import Protocol, runtime_checkable
from core.domain.machine import MachineProfile
from core.domain.telemetry import TelemetrySnapshot
from core.domain.hardware import HardwareEvent

@runtime_checkable
class IHardwareSDK(Protocol):
    async def discover(self) -> MachineProfile: ...
    async def get_profile(self) -> MachineProfile: ...
    async def get_telemetry(self) -> TelemetrySnapshot: ...
    async def get_events(self) -> tuple[HardwareEvent, ...]: ...
    async def subscribe(self, event_type: str, handler) -> None: ...
