from __future__ import annotations
from typing import Protocol, runtime_checkable
from core.domain.execution import ExecutionResult

@runtime_checkable
class IInstallerSDK(Protocol):
    async def install(self, package: str, options: dict | None = None) -> ExecutionResult: ...
    async def uninstall(self, package: str) -> ExecutionResult: ...
    async def repair(self, package: str) -> ExecutionResult: ...
    async def list_installed(self) -> tuple[str, ...]: ...
