from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class IKnowledgeSDK(Protocol):
    async def add_document(self, text: str, metadata: dict | None = None) -> str: ...
    async def search(self, query: str, top_k: int = 3) -> list[dict]: ...
    async def clear(self) -> None: ...
