from __future__ import annotations
from typing import Protocol, runtime_checkable
from core.domain.models import InstalledModel, ModelDescriptor

@runtime_checkable
class IModelSDK(Protocol):
    async def list_installed(self) -> tuple[InstalledModel, ...]: ...
    async def list_available(self) -> tuple[ModelDescriptor, ...]: ...
    async def download(self, model_name: str) -> bool: ...
    async def get_path(self, model_name: str) -> str | None: ...
    async def delete(self, model_name: str) -> bool: ...
