from __future__ import annotations
from typing import Protocol, runtime_checkable, Any

@runtime_checkable
class IObservabilitySDK(Protocol):
    async def log_event(self, engine: str, level: str, message: str, data: dict | None = None) -> None: ...
    async def get_platform_health(self) -> dict[str, Any]: ...
    async def get_logs(self, limit: int = 20) -> list[dict]: ...
    async def get_event_history(self, event_type: str = None, limit: int = 50) -> list[dict]: ...
