from __future__ import annotations
from typing import Protocol, runtime_checkable, Any

@runtime_checkable
class IPluginManagerSDK(Protocol):
    async def list_plugins(self) -> list[dict]: ...
    async def enable_plugin(self, plugin_id: str) -> bool: ...
    async def disable_plugin(self, plugin_id: str) -> bool: ...
    async def install_plugin(self, source_path: str) -> str: ...
