from __future__ import annotations
from typing import Protocol, runtime_checkable
from core.domain.execution import ExecutionPlan, ExecutionResult
from core.domain.runtime import RuntimeDescriptor, RuntimeStatus

@runtime_checkable
class IRuntimeSDK(Protocol):
    async def list_runtimes(self) -> tuple[RuntimeDescriptor, ...]: ...
    async def start(self, runtime: str) -> bool: ...
    async def stop(self, runtime: str) -> bool: ...
    async def status(self, runtime: str) -> RuntimeStatus: ...
    async def execute(self, plan: ExecutionPlan) -> ExecutionResult: ...
    async def pull_model(self, runtime: str, model_name: str) -> bool: ...
    async def embed(self, runtime: str, model: str, text: str) -> list[float]: ...
    async def describe_image(self, runtime: str, model: str, prompt: str, image_path: str) -> str: ...
