from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class ISchedulerSDK(Protocol):
    async def schedule_mission(self, mission_name: str, interval_minutes: int) -> str: ...
    async def list_schedules(self) -> list[dict]: ...
    async def cancel_schedule(self, schedule_id: str) -> bool: ...
