from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class ISecuritySDK(Protocol):
    async def store_secret(self, key: str, value: str) -> None: ...
    async def get_secret(self, key: str) -> str | None: ...
    async def delete_secret(self, key: str) -> None: ...
    async def get_or_create_api_key(self) -> str: ...
