from __future__ import annotations
from typing import Protocol, runtime_checkable
from pathlib import Path

@runtime_checkable
class IStorageSDK(Protocol):
    async def get_fastest_drive(self) -> str: ...
    async def get_workspace_path(self) -> Path: ...
    async def get_models_path(self) -> Path: ...
    async def get_disk_info(self) -> list[dict]: ...
    async def ensure_directory(self, path: str | Path) -> Path: ...
    async def get_free_space_gb(self, path: str | Path) -> float: ...
