import React, { useEffect, useMemo, useState } from 'react';
import { Check, Copy, Cpu, Download, FileText, Shield, X } from 'lucide-react';

interface Props { isOpen: boolean; onClose: () => void }
const bytes = (v?: number) => typeof v === 'number' ? `${(v / 1024 ** 3).toFixed(1)} GB` : 'não informado';
const Row = ({ label, value }: { label: string; value: React.ReactNode }) => <div className="flex justify-between gap-4 py-1 border-b border-[#14141c] last:border-0"><span className="text-[#6f7884]">{label}</span><span className="text-white text-right break-all">{value}</span></div>;

export const SystemReportModal: React.FC<Props> = ({ isOpen, onClose }) => {
  const [report, setReport] = useState<any>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(false), [copied, setCopied] = useState(false), [jsonView, setJsonView] = useState(false);
  const [deviceLabel, setDeviceLabel] = useState(''), [deviceIndex, setDeviceIndex] = useState(0), [romPath, setRomPath] = useState(''), [qualificationProfile, setQualificationProfile] = useState('standard'), [qualificationBusy, setQualificationBusy] = useState(false), [qualificationMessage, setQualificationMessage] = useState('');
  useEffect(() => {
    if (!isOpen) return;
    const c = new AbortController(), timer = setTimeout(() => c.abort(), 65000);
    setLoading(true); setError(null); setReport(null);
    fetch('/api/forge/report', { signal: c.signal }).then(async r => { const b = await r.json().catch(() => ({})); if (!r.ok) throw new Error(b.detail || b.error || `HTTP ${r.status}`); return b; }).then(setReport).catch(e => setError(e?.name === 'AbortError' ? 'O Phoenix Forge excedeu 65 segundos durante a coleta.' : e?.message || String(e))).finally(() => { clearTimeout(timer); setLoading(false); });
    return () => { clearTimeout(timer); c.abort(); };
  }, [isOpen]);
  const json = useMemo(() => JSON.stringify(report, null, 2), [report]);
  if (!isOpen) return null;
  const copy = async () => { if (!report) return; await navigator.clipboard.writeText(json); setCopied(true); setTimeout(() => setCopied(false), 2000); };
  const download = () => { if (!report) return; const u = URL.createObjectURL(new Blob([json], { type: 'application/json' })), a = document.createElement('a'); a.href = u; a.download = `phoenix-forge-report-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(u); };
  const captureQualification = async (phase: 'PRE_FLASH' | 'POST_FLASH') => {
    if (!deviceLabel.trim()) { setQualificationMessage('Informe o rótulo físico da placa.'); return; }
    setQualificationBusy(true); setQualificationMessage('');
    try {
      const r = await fetch('/api/forge/gpu-qualification/capture', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ device_label: deviceLabel.trim(), phase, device_index: deviceIndex, vbios_path: romPath.trim() || null }) });
      const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error(body.detail || body.error || `HTTP ${r.status}`);
      setQualificationMessage(`${phase} registrado · chave ${body.device_key} · SHA ${body.record_sha256?.slice(0, 12)}…`);
    } catch (e: any) { setQualificationMessage(e?.message || String(e)); } finally { setQualificationBusy(false); }
  };
  const runPostFlashQualification = async () => {
    if (!deviceLabel.trim()) { setQualificationMessage('Informe o rótulo físico da placa.'); return; }
    setQualificationBusy(true); setQualificationMessage('Qualificação pós-flash em execução. Não interrompa a Phoenix durante o teste.');
    try {
      const r = await fetch('/api/forge/gpu-qualification/post-flash/run', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ device_label: deviceLabel.trim(), device_index: deviceIndex, profile: qualificationProfile }) });
      const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error(body.detail || body.error || `HTTP ${r.status}`);
      setQualificationMessage(`Pós-flash: ${body.status} · ${body.steps?.length ?? 0} etapa(s) · GPU ${body.device_index}`);
    } catch (e: any) { setQualificationMessage(e?.message || String(e)); } finally { setQualificationBusy(false); }
  };
  const gpus = report?.hardware?.gpus || [];
  const gpu = gpus[deviceIndex] || gpus[0], safety = report?.gpu_safety, supervisor = report?.engine_supervisor;
  const gate = report?.quality_gate, fault = report?.fault_correlation;
  const states = Object.values(report?.workload_states?.workloads || {}) as any[];
  const inspector = report?.hardware_inspector, parity = report?.parity_matrix;
  const products = Object.entries(parity?.products || {}) as [string, any][];
  const missingProviders = inspector?.missing_providers || [];
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm"><div className="w-full max-w-3xl bg-[#0d0d12] border border-[#252532] rounded-lg max-h-[90vh] overflow-hidden flex flex-col text-[#e0e0e0] font-mono">
    <header className="px-6 py-4 border-b border-[#252532] flex justify-between"><div><h2 className="text-base font-bold tracking-[.16em] uppercase text-white">Phoenix Forge // relatório verificável</h2><p className="text-xs text-[#6f7884] mt-1">Hardware, segurança, Quality Gate, correlação e decisões reais.</p></div><button onClick={onClose}><X className="w-5 h-5" /></button></header>
    <div className="px-6 py-2.5 border-b border-[#252532] flex justify-between"><span className={error ? 'text-[#ff6175]' : report ? 'text-[#37d67a]' : 'text-[#8d98a5]'}>{loading ? 'COLETANDO…' : error ? 'INDISPONÍVEL' : report ? 'RELATÓRIO RECEBIDO' : 'AGUARDANDO'}</span><div className="flex gap-3 text-[11px]"><button disabled={!report} onClick={() => setJsonView(!jsonView)} className="text-[#4fa3ff] disabled:opacity-40 flex gap-1"><FileText className="w-3 h-3" />{jsonView ? 'Visual' : 'JSON'}</button><button disabled={!report} onClick={copy} className="text-[#37d67a] disabled:opacity-40 flex gap-1">{copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}{copied ? 'Copiado' : 'Copiar'}</button><button disabled={!report} onClick={download} className="text-[#8d98a5] disabled:opacity-40 flex gap-1"><Download className="w-3 h-3" />Baixar</button></div></div>
    <main className="flex-1 overflow-y-auto p-6 text-xs">{error && <div className="p-4 border border-[#ff334b]/50 bg-[#ff334b]/10 text-[#ff8b9a]">{error}</div>}{loading && !report && <div className="text-[#8d98a5]">Consultando Engine → Phoenix Forge…</div>}{report && jsonView && <pre className="p-4 bg-[#050508] border border-[#252532] rounded text-[#4fa3ff] overflow-x-auto">{json}</pre>}{report && !jsonView && <div className="space-y-4">
      <div className="grid md:grid-cols-2 gap-4"><section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#4fa3ff] mb-3 flex gap-2"><Cpu className="w-4 h-4" />Hardware</h3><Row label="CPU" value={report.hardware?.cpu || 'não informado'} /><Row label="Threads" value={report.hardware?.logical_cpus ?? '—'} /><Row label="RAM" value={bytes(report.hardware?.ram_total_bytes)} /><Row label="GPU" value={gpu?.name || 'não informada'} /><Row label="VRAM" value={bytes(gpu?.vram_bytes || gpu?.memory_total_bytes)} /><Row label="Driver" value={gpu?.driver_version || '—'} /></section><section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#37d67a] mb-3 flex gap-2"><Shield className="w-4 h-4" />Forge e segurança</h3><Row label="Versão" value={report.forge?.version || '—'} /><Row label="Orquestração" value={report.orchestration_state || '—'} /><Row label="Propriedade" value={supervisor?.ownership || '—'} /><Row label="PID" value={supervisor?.pid ?? '—'} /><Row label="Saúde GPU" value={safety?.device_health || '—'} /><Row label="Autorização" value={safety?.authorization?.state || '—'} /></section></div>
      <section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#f0b429] mb-3">Quality Gate e correlação</h3><Row label="Gate do último benchmark" value={gate?.status || 'SEM BENCHMARK'} /><Row label="Elegível para baseline" value={gate?.baseline_eligible === true ? 'SIM' : gate ? 'NÃO' : '—'} /><Row label="Causa provável" value={fault?.probable_cause || 'SEM EVIDÊNCIA'} /><Row label="Confiança" value={typeof fault?.confidence === 'number' ? `${Math.round(fault.confidence * 100)}%` : '—'} /><Row label="Severidade" value={fault?.severity || '—'} />{gate?.reasons?.length > 0 && <p className="mt-3 text-[#ff8b9a]">Bloqueios: {gate.reasons.join(', ')}</p>}</section>
      <section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#4fa3ff] mb-3">Estado por workload</h3>{states.length ? states.map((item: any) => <Row key={item.workload} label={String(item.workload).toUpperCase()} value={`${item.state} · ${item.effective_mode}`} />) : <p className="text-[#6f7884]">Estados serão registrados conforme as rotas forem usadas.</p>}</section>
      <section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#37d67a] mb-3">Cobertura verificável</h3>{products.length ? products.map(([name, value]) => <Row key={name} label={name} value={`${value.coverage_percent}% · ${value.done} concluídas · ${value.partial} parciais · ${value.missing} ausentes`} />) : <p className="text-[#6f7884]">Matriz disponível a partir do Forge 0.16.0.</p>}<p className="mt-3 text-[#6f7884]">Equivalência funcional própria; nenhum binário Phoenix CPU Inspector, Phoenix GPU Inspector ou Phoenix Stress & Correctness é incorporado.</p></section>
      <section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#f0b429] mb-3">Proveniência e limitações</h3><Row label="Inspeção" value={inspector?.status || 'INDISPONÍVEL'} /><Row label="Ausência significa falha" value={inspector?.absence_is_failure === false ? 'NÃO' : '—'} /><Row label="Provedores ausentes" value={missingProviders.length ? missingProviders.join(', ') : 'nenhum'} />{(inspector?.limitations || []).map((item: string) => <p key={item} className="mt-2 text-[#8d98a5]">• {item}</p>)}</section>
      <section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#ff6175] mb-3">VBIOS // Histórico e qualificação</h3><p className="text-[#8d98a5] mb-3">Selecione a GPU real. O device_key identificado pelo Forge é a identidade técnica persistente; o rótulo abaixo é apenas um alias físico confirmado por você. O caminho da ROM é opcional e permanece local.</p><div className="grid md:grid-cols-2 gap-2"><select value={deviceIndex} onChange={e=>setDeviceIndex(Number(e.target.value))} className="bg-[#050508] border border-[#252532] rounded px-3 py-2 text-white">{gpus.map((item:any,index:number)=><option key={`${item.pnp_device_id || item.name}-${index}`} value={index}>GPU {index} · {item.name || 'GPU'} · {item.device_id || '?'}</option>)}</select><input value={deviceLabel} onChange={e=>setDeviceLabel(e.target.value)} placeholder="Alias físico (ex.: RX580-XFX)" className="bg-[#050508] border border-[#252532] rounded px-3 py-2 text-white" /><input value={romPath} onChange={e=>setRomPath(e.target.value)} placeholder="C:\\...\\backup.rom (opcional)" className="bg-[#050508] border border-[#252532] rounded px-3 py-2 text-white" /><select value={qualificationProfile} onChange={e=>setQualificationProfile(e.target.value)} className="bg-[#050508] border border-[#252532] rounded px-3 py-2 text-white"><option value="quick">Rápido</option><option value="standard">Padrão</option><option value="deep">Profundo</option></select></div><div className="flex flex-wrap gap-2 mt-3"><button disabled={qualificationBusy} onClick={()=>captureQualification('PRE_FLASH')} className="px-3 py-2 border border-[#4fa3ff]/50 text-[#4fa3ff] rounded disabled:opacity-40">Capturar estado atual</button><button disabled={qualificationBusy} onClick={()=>captureQualification('POST_FLASH')} className="px-3 py-2 border border-[#f0b429]/50 text-[#f0b429] rounded disabled:opacity-40">Associar como pós-alteração</button><button disabled={qualificationBusy} onClick={runPostFlashQualification} className="px-3 py-2 border border-[#ff6175]/50 text-[#ff6175] rounded disabled:opacity-40">Comparar / qualificar</button></div><Row label="GPU selecionada" value={`GPU ${deviceIndex} · ${gpu?.name || 'não informada'}`} /><Row label="device_key persistente" value={gpu?.device_key || 'não informado'} /><Row label="Alias físico" value={deviceLabel.trim() || 'não confirmado'} /><Row label="Registros armazenados" value={report.gpu_qualification?.count ?? 0} />{qualificationMessage && <p className="mt-2 text-[#37d67a] break-all">{qualificationMessage}</p>}<p className="mt-3 text-[#ff8b9a]">O Forge não grava firmware. O alias físico não substitui o device_key. Um mismatch é repetido uma vez; somente corrupção reproduzível vira evidência física. OOM/timeout continuam sendo capacidade.</p></section>
      <section className="p-4 bg-[#09090e] border border-[#252532] rounded"><h3 className="uppercase text-[#f0b429] mb-3">Evidências</h3><Row label="Benchmarks salvos" value={report.benchmark_history?.count ?? 0} /><Row label="Decisões de entrega" value={report.executions?.count ?? 0} /><Row label="Golden Baseline" value={report.baseline?.available ? 'criada e imutável' : 'ainda não criada'} /><Row label="Falhas GPU" value={safety?.failure_count ?? 0} /><Row label="Modo efetivo" value={safety?.authorization?.effective_mode || '—'} /><p className="mt-3 text-[#f0b429]">{safety?.notice || safety?.message || 'Nenhum aviso adicional.'}</p></section>
    </div>}</main>
  </div></div>;
};
