#include "phoenix_msr_abi.h"
#include <windows.h>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <future>
#include <cstdint>
#include <algorithm>

static std::string json_escape(const std::string& s){std::ostringstream o;for(char c:s){if(c=='\\'||c=='"')o<<'\\'<<c;else if(c=='\n')o<<"\\n";else if(c=='\r')o<<"\\r";else o<<c;}return o.str();}
static std::string extract_string(const std::string& s,const std::string& key){const std::string n="\""+key+"\"";auto p=s.find(n);if(p==std::string::npos)return{};p=s.find(':',p+n.size());if(p==std::string::npos)return{};p=s.find('"',p+1);if(p==std::string::npos)return{};auto e=s.find('"',p+1);if(e==std::string::npos)return{};return s.substr(p+1,e-p-1);}
static unsigned extract_uint(const std::string& s,const std::string& key,unsigned fallback){const std::string n="\""+key+"\"";auto p=s.find(n);if(p==std::string::npos)return fallback;p=s.find(':',p+n.size());if(p==std::string::npos)return fallback;++p;while(p<s.size()&&(s[p]==' '||s[p]=='\t'))++p;unsigned v=0;bool any=false;while(p<s.size()&&s[p]>='0'&&s[p]<='9'){any=true;v=v*10u+unsigned(s[p]-'0');++p;}return any?v:fallback;}
static HANDLE open_device(){constexpr DWORD kDesiredAccess=0x80000000UL;constexpr DWORD kShareMode=FILE_SHARE_READ|FILE_SHARE_WRITE;return CreateFileW(PHOENIX_MSR_DEVICE,kDesiredAccess,kShareMode,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);}
static bool get_info(HANDLE h,PfMsrInfoV1& info){DWORD got=0;ZeroMemory(&info,sizeof(info));return DeviceIoControl(h,PFMSR_IOCTL_GET_INFO,nullptr,DWORD{0},&info,DWORD(sizeof(info)),&got,nullptr)&&got>=DWORD(sizeof(info))&&info.abi_version==PHOENIX_MSR_ABI_VERSION;}
static void handshake(){HANDLE h=open_device();PfMsrInfoV1 info{};bool driver=(h!=INVALID_HANDLE_VALUE)&&get_info(h,info);if(h!=INVALID_HANDLE_VALUE)CloseHandle(h);std::cout<<"{\"schema\":\"phoenix.forge.provider-handshake/v1\",\"name\":\"phoenix-msr-windows\",\"version\":\"0.25.0rc6.post3\",\"privilege\":\"kernel-driver-required\",\"capabilities\":[";bool first=true;if(driver&&(info.capability_bits&PFMSR_CAP_APERF_MPERF)){std::cout<<"\"clock.aperf_mperf\"";first=false;}if(driver&&(info.capability_bits&PFMSR_CAP_BCLK_MULTIPLIER)){if(!first)std::cout<<',';std::cout<<"\"clock.bclk_multiplier\"";}std::cout<<"],\"driver_status\":\""<<(driver?"READY":"MISSING")<<"\",\"abi_version\":"<<PHOENIX_MSR_ABI_VERSION<<"}";}
static void respond(const std::string& id,const std::string& cap,const std::string& status,const std::string& data,const std::string& evidence="[]"){std::cout<<"{\"schema\":\"phoenix.forge.provider-response/v1\",\"request_id\":\""<<json_escape(id)<<"\",\"capability\":\""<<json_escape(cap)<<"\",\"status\":\""<<status<<"\",\"data\":"<<data<<",\"evidence\":"<<evidence<<"}";}
struct SampleRow{bool ok=false;WORD group=0;DWORD number=0;std::uint64_t aperf=0,mperf=0;double ref=0.0;DWORD error=0;};
static SampleRow sample_one(WORD g,DWORD n,DWORD sampling_ms){SampleRow row{};row.group=g;row.number=n;HANDLE h=open_device();if(h==INVALID_HANDLE_VALUE){row.error=GetLastError();return row;}PfMsrInfoV1 info{};if(!get_info(h,info)||(info.capability_bits&PFMSR_CAP_APERF_MPERF)==0){row.error=ERROR_NOT_SUPPORTED;CloseHandle(h);return row;}PfMsrCounterRequestV1 in{PHOENIX_MSR_ABI_VERSION,static_cast<std::uint16_t>(g),static_cast<std::uint16_t>(n),sampling_ms};PfMsrCounterResultV1 out{};DWORD got=0;BOOL ok=DeviceIoControl(h,PFMSR_IOCTL_READ_COUNTER_PAIR,&in,DWORD(sizeof(in)),&out,DWORD(sizeof(out)),&got,nullptr);if(!ok){row.error=GetLastError();CloseHandle(h);return row;}CloseHandle(h);if(got<DWORD(sizeof(out))||out.abi_version!=PHOENIX_MSR_ABI_VERSION||out.processor_group!=g||out.processor_number!=n){row.error=ERROR_INVALID_DATA;return row;}row.ok=true;row.aperf=out.aperf_delta;row.mperf=out.mperf_delta;row.ref=out.reference_mhz;return row;}
static int call_provider(const std::string& capability){std::ostringstream ss;ss<<std::cin.rdbuf();const std::string req=ss.str();const std::string id=extract_string(req,"request_id");HANDLE h=open_device();if(h==INVALID_HANDLE_VALUE){respond(id,capability,"UNAVAILABLE","{\"driver_status\":\"MISSING\"}");return 0;}PfMsrInfoV1 info{};if(!get_info(h,info)){CloseHandle(h);respond(id,capability,"UNAVAILABLE","{\"driver_status\":\"ABI_MISMATCH\"}");return 0;}CloseHandle(h);if(capability!="clock.aperf_mperf"){respond(id,capability,"UNAVAILABLE","{\"reason\":\"NOT_IMPLEMENTED_BY_PROVIDER\"}");return 0;}if((info.capability_bits&PFMSR_CAP_APERF_MPERF)==0){respond(id,capability,"UNAVAILABLE","{\"driver_status\":\"CAPABILITY_NOT_EXPOSED\"}");return 0;}DWORD sampling_ms=extract_uint(req,"sampling_ms",100u);sampling_ms=std::max<DWORD>(50u,std::min<DWORD>(sampling_ms,500u));struct Target{WORD g;DWORD n;DWORD flat;};std::vector<Target> targets;DWORD flat=0;WORD groups=GetActiveProcessorGroupCount();for(WORD g=0;g<groups;++g){DWORD count=GetActiveProcessorCount(g);for(DWORD n=0;n<count;++n)targets.push_back(Target{g,n,flat++});}if(targets.size()>256u){respond(id,capability,"ERROR","{\"reason\":\"TOO_MANY_LOGICAL_PROCESSORS\"}");return 0;}std::vector<std::future<SampleRow>> jobs;jobs.reserve(targets.size());for(const auto& x:targets)jobs.emplace_back(std::async(std::launch::async,[x,sampling_ms](){return sample_one(x.g,x.n,sampling_ms);}));std::ostringstream data;data<<"{\"sampling_ms\":"<<sampling_ms<<",\"parallel\":true,\"samples\":[";bool first=true;std::size_t failures=0;for(std::size_t i=0;i<jobs.size();++i){SampleRow r=jobs[i].get();const auto& x=targets[i];if(!r.ok){++failures;continue;}if(!first)data<<',';first=false;data<<"{\"logical_cpu\":"<<x.flat<<",\"processor_group\":"<<r.group<<",\"processor_number\":"<<r.number<<",\"aperf_delta\":"<<r.aperf<<",\"mperf_delta\":"<<r.mperf<<",\"reference_mhz\":"<<r.ref<<"}";}data<<"],\"requested_cpu_count\":"<<targets.size()<<",\"failed_cpu_count\":"<<failures<<"}";respond(id,capability,first?"UNAVAILABLE":(failures?"PARTIAL":"OK"),data.str(),"[{\"source\":\"PhoenixForgeMsr ABI v1\",\"kind\":\"kernel_driver\",\"sampling\":\"parallel\"}]");return 0;}
int main(int argc,char**argv){if(argc>=2&&std::string(argv[1])=="--phoenix-provider-handshake"){handshake();return 0;}if(argc>=3&&std::string(argv[1])=="--phoenix-provider-call"){return call_provider(argv[2]);}return 2;}
